### ISSUE TITLE
AttributeError: module 'sqlmodel.sql.sqltypes' has no attribute 'GUID'

### ISSUE THREAD

**Issue by byronrode** [piercefreeman/mountaineer#123]
I get the following error when trying to run either `poetry run createdb` or `poetry run runserver`.

```
❯ poetry run createdb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/byronrode/.pyenv/versions/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/byronrode/Code/Personal/Python/moutaineer-test/moutaineer_test/cli.py", line 5, in <module>
    from mountaineer.migrations.cli import handle_apply, handle_generate, handle_rollback
  File "/Users/byronrode/Library/Caches/pypoetry/virtualenvs/moutaineer-test-EcWe_Swf-py3.12/lib/python3.12/site-packages/mountaineer/migrations/cli.py", line 14, in <module>
    from mountaineer.migrations.generator import MigrationGenerator
  File "/Users/byronrode/Library/Caches/pypoetry/virtualenvs/moutaineer-test-EcWe_Swf-py3.12/lib/python3.12/site-packages/mountaineer/migrations/generator.py", line 15, in <module>
    from mountaineer.migrations.db_memory_serializer import DatabaseMemorySerializer
  File "/Users/byronrode/Library/Caches/pypoetry/virtualenvs/moutaineer-test-EcWe_Swf-py3.12/lib/python3.12/site-packages/mountaineer/migrations/db_memory_serializer.py", line 13, in <module>
    from mountaineer.migrations.handlers import (
  File "/Users/byronrode/Library/Caches/pypoetry/virtualenvs/moutaineer-test-EcWe_Swf-py3.12/lib/python3.12/site-packages/mountaineer/migrations/handlers.py", line 589, in <module>
    sa.UUID | sqltypes.GUID | sa.Float | sa.String | sa.Boolean | sa.Integer | sa.JSON
              ^^^^^^^^^^^^^
AttributeError: module 'sqlmodel.sql.sqltypes' has no attribute 'GUID'
```

I used the quickstart `pipx run create-mountaineer-app`

This happens both with the Docker version of Postgres, as well as with my actual Postgres.app.

```
Poetry Version: 1.8.3
Python Version: 3.12.3
```

## Packages

<img width="594" alt="image" src="https://github.com/user-attachments/assets/729b5d46-a635-47b1-8dc7-8af68f404e3b">

**Comment by piercefreeman** [comment]
Hi @byronrode, this should be addressed in the latest dev release at https://github.com/piercefreeman/mountaineer/releases/tag/v0.5.2.dev1. It was caused by an internal change that SQLModel used to align with the new postgres conventions.

Let me know if you still see it in the latest version. There should be a fully baked new 0.6.0 with more functionality and this fix coming soon.

**Comment by byronrode** [comment]
Thanks @piercefreeman - installing the dev version worked. Appreciate the update.

**Comment by piercefreeman** [comment]
@byronrode This is now launched in stable 0.6.0, alongside with some other nice-to-haves around typehinting:
https://github.com/piercefreeman/mountaineer/releases/tag/v0.6.0

**Comment by byronrode** [comment]
Amazing. I'll remove the pin to dev over the weekend.
