### ISSUE TITLE
"Could not find a valid path for package" when running "poetry run runserver"

### ISSUE THREAD

**Issue by hashring** [piercefreeman/mountaineer#40]
Folks, great work on Mountaineer, it really looks promising.

I am encountering the following issue when following the quickstart steps from the README:

```
pipx run create-mountaineer-app
...
cd <project-dir>
docker-compose up -d
poetry run createdb
...
poetry run runserver
```

```
{"level": "DEBUG", "name": "mountaineer.logging", "message": "Starting WatcherWebservice on port 61552"}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steps/Projects/MyMountaineerApp/MyMountaineerApp/cli.py", line 13, in runserver
    handle_runserver(
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mountaineer/cli.py", line 265, in handle_runserver
    watchdog = build_common_watchdog(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mountaineer/cli.py", line 331, in build_common_watchdog
    return PackageWatchdog(
           ^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mountaineer/watch.py", line 140, in __init__
    self.get_package_paths()
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mountaineer/watch.py", line 182, in get_package_paths
    package_path = self.resolve_package_path(dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mountaineer/watch.py", line 231, in resolve_package_path
    raise ValueError(
ValueError: Could not find a valid path for package MyMountaineerApp, found files: [PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp.pth'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/bin/build'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/bin/createdb'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/bin/runserver'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/bin/watch'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp-0.1.0.dist-info/METADATA'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp-0.1.0.dist-info/INSTALLER'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp-0.1.0.dist-info/entry_points.txt'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp-0.1.0.dist-info/direct_url.json'), PackagePath('/Users/steps/Library/Caches/pypoetry/virtualenvs/mymountaineerapp-WihrTrTk-py3.11/lib/python3.11/site-packages/mymountaineerapp-0.1.0.dist-info/RECORD')]
```

Are we missing a step in the README, or is there an environment issue which should be called out in the documentation? Appreciate any pointers!

**Comment by piercefreeman** [comment]
Hey @hashring, thanks for the report.

It looks like your package.name is MyMountaineerApp (with caps). The current package sniffing logic https://github.com/piercefreeman/mountaineer/blob/main/mountaineer/watch.py#L196 expects the case of the `mymountaineerapp.pth` file to match exactly. I'll put up a quick PR to fix this and get this in the next release patch.

For the time-being if you want to unblock yourself, you can start a new project with lowercase casing.

**Comment by piercefreeman** [comment]
This should be fixed in the latest `main` codebase. Let me know if that solves your issue @hashring.

**Comment by hashring** [comment]
Hey Pierce,

awesome, thanks a lot. Happy to confirm the issue is fixed by this.
